### PR TITLE
Add support for time value

### LINKED ISSUE #41: Support knora-api:timeValue
implement support for https://github.com/dhlab-basel/Knora/pull/1403

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR adds support for time value.

closes #41 
relates to https://github.com/dhlab-basel/Knora/pull/1403

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
This PR can be merged once dhlab-basel/Knora#1403 has been merged.

**Comment by andreas-aeschlimann** [comment]
Should we consider using a library like https://momentjs.com/? Or do we leave this up to the end developer?

Date/time causes a lot of problems in JavaScript, especially due to timezone issues.

See also https://github.com/dhlab-basel/Knora-ui/issues/132

**Comment by tobiasschweizer** [comment]
> Should we consider using a library like https://momentjs.com/? Or do we leave this up to the end developer?

> Date/time causes a lot of problems in JavaScript, especially due to timezone issues.

> See also dhlab-basel/Knora-ui#132

dhlab-basel/Knora-ui#132 was never resolved and is also hard to reproduce. 

I think we could at least offer a convenience function for `ReadTimeValue` that parses the string representation, so it would be easier to handle the information contained in it. Displaying it nicely should be left to @knora-ui/viewer.

**Comment by tobiasschweizer** [comment]
@lrosenth This PR is up to date and ready to be merged whenever https://github.com/dasch-swiss/knora-api/pull/1403 is. Please coordinate with @subotic

**Comment by tobiasschweizer** [comment]
Ok, I think this PR is done can can be merged when https://github.com/dasch-swiss/knora-api/pull/1403 is ready.

**Pull request merged**
