### PR TITLE
Add integration test

### PR DESCRIPTION
**Pull request by subotic**

### CODE REVIEW

**Comment by subotic** [comment]
@tobiasschweizer There seems to be a small problem with a test. Can you please take a look?

**Comment by tobiasschweizer** [comment]
> There seems to be a small problem with a test. Can you please take a look?

see https://github.com/dasch-swiss/knora-api/pull/1577#issuecomment-590199729

**Comment by subotic** [comment]
I've commented out the test and created a new issue #153.

**Comment by subotic** [comment]
@tobiasschweizer It passes now. Could you please review?

**Pull request merged**
