### PR TITLE
add method to create a resource

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Add method to create a resource.

### CODE REVIEW

**Comment by benjamingeer** [comment]
OK, will do.

**Comment by tobiasschweizer** [comment]
note to myself: understand JS number precision https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript

**Comment by tobiasschweizer** [comment]
@benjamingeer I had to change "100000000000000.000000000000001" to 1.5

**Comment by benjamingeer** [comment]
> I had to change "100000000000000.000000000000001" to 1.5

https://www.npmjs.com/package/js-big-decimal

**Comment by tobiasschweizer** [comment]
Yes, I saw his too (https://github.com/dasch-swiss/knora-api/pull/1549#issuecomment-564599052). Yet another dependency ...

**Comment by benjamingeer** [comment]
> Yes, I saw his too (dasch-swiss/knora-api#1549 (comment)). Yet another dependency ...

Or you can just use `string`. But we can't lose precision, that would be equivalent to losing data.

**Comment by tobiasschweizer** [comment]
> Or you can just use string. But we can't lose precision, that would be equivalent to losing data.

I will look at this and try to figure something out. I remember that we had this problem in Scala too before using `BigDecimal`.

**Comment by tobiasschweizer** [comment]
@benjamingeer I think I will create a separate issue to deal with precisions

**Pull request merged**
