### PR TITLE
Export mock factory and test data

### LINKED ISSUE #121: MockFactory needed for tests
a MockFactory is needed at least for the tests in Knora-ui modules to be able to get test data, get mocked objects (especially complex ones like ReadDateValue and ReadGeomValue)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
closes #121

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
It is possible to include mock factory methods and referenced test data in the package but this makes it heave. Maybe there should be a dev version of the package and one for productive use.

**Comment by tobiasschweizer** [comment]
@subotic This PR contains the necessary changes to produce a dev version of the package. I think I will be able to set up an automated publication process where:
- a new productive build is published
- the same version of the build is published with some additional code needed to generate test data

I think the convention could be that if "1.0.0-rc.0" is the productive version, "1.0.0-devrc.0" would be published in parallel (or "1.0.0" and "1.0.0-dev"). I think the dev version should always be treated as a prerelease.

However, I still need to make sure that it works correctly with semantic versioning.

**Comment by SepidehAlassi** [comment]
@tobiasschweizer this branch is out-of-date. Can you please update it? or should I?

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer this branch is out-of-date. Can you please update it? or should I?

This branch will be deleted, please use https://www.npmjs.com/package/@knora/api/v/1.0.0-rc.0
See https://github.com/dasch-swiss/knora-ui-ng-lib/pull/76#issuecomment-625755276 for further details.

**Pull request closed without merging**
