### PR TITLE
Expand ontology service

### PR DESCRIPTION
**Pull request by kilchenmann**
Resolves [DSP-71](https://dasch.myjetbrains.com/youtrack/issue/DSP-71)

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
to see how the create resource method was implemented, you can have look at

https://github.com/dasch-swiss/knora-api-js-lib/blob/7c38e545ec026e1707482152668a7b3e76183f83/src/api/v2/resource/resources-endpoint-v2.ts#L79

**Comment by tobiasschweizer** [comment]
@kilchenmann Can this PR be closed since you are working on a different branch now?

**Comment by kilchenmann** [comment]
@tobiasschweizer I can close the PR but I will keep the branch for the moment. I need some information from this branch for the next two ontology PRs

**Comment by tobiasschweizer** [comment]
Ok, no problem. Just delete the branch once you don't need it anymore.

**Pull request closed without merging**
