### PR TITLE
Add missing decorator

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Fixes an issue caused by a missing decorator.

### CODE REVIEW

**Comment by andreas-aeschlimann** [comment]
Let's hope it's the only event of a missing decorator in the project. Otherwise it's good to go.

**Comment by tobiasschweizer** [comment]
> Let's hope it's the only event of a missing decorator in the project. 

I think then more tests would fail.

**Comment by tobiasschweizer** [comment]
Have you ever seen a thing like this 

> ##[error]ERROR in node_modules/json2typescript/src/json2typescript/json-convert.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
1656
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
1657
Hash: b3c99c0b739debe23b87
1658
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(57,9): error TS1086: An accessor cannot be declared in an ambient context.
1659
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(68,9): error TS1086: An accessor cannot be declared in an ambient context.
1660
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(80,9): error TS1086: An accessor cannot be declared in an ambient context.
1661
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(87,9): error TS1086: An accessor cannot be declared in an ambient context.
1662
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(105,9): error TS1086: An accessor cannot be declared in an ambient context.
1663
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(115,9): error TS1086: An accessor cannot be declared in an ambient context.
1664
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(131,9): error TS1086: An accessor cannot be declared in an ambient context.
1665
##[error]node_modules/json2typescript/src/json2typescript/json-convert.d.ts(140,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by tobiasschweizer** [comment]
looks like a compiler problem: https://github.com/storybookjs/storybook/issues/9463

**Comment by andreas-aeschlimann** [comment]
Yes:
https://github.com/AppVision-GmbH/json2typescript/pull/126

Upgrade to Angular 8 which supports TypeScript 3.5+ should solve the issue.

I will try to fix it in the d.ts files when I find out how.

**Comment by tobiasschweizer** [comment]
> Yes:
> [AppVision-GmbH/json2typescript#126](https://github.com/AppVision-GmbH/json2typescript/pull/126)
> 
> Upgrade to Angular 8 which supports TypeScript 3.5+ should solve the issue.
> 
> I will try to fix it in the d.ts files when I find out how.

I have already made a PR for the update to Angular 9: #172 

For now, I have adapted `package.json` so that it does not update to `json2typescript` 1.3.0.

**Pull request merged**
