### PR TITLE
Fix security vulnerability

### PR DESCRIPTION
**Pull request by kilchenmann**
Github reported a security alert for minimist. So, I updated the npm packages with `npm audit fix` to resolve the following issue:

Screen Shot 2020-05-29 at 15 15 54

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I will. This week is just crazy ...

**Comment by kilchenmann** [comment]
No hurry. I don't wanted to stress you. I wasn't sure if you saw it and I never mentioned this PR in the scrum meetings.

**Comment by tobiasschweizer** [comment]
no problem :-)

**Comment by tobiasschweizer** [comment]
ok, I'll check this PR now

**Comment by tobiasschweizer** [comment]
When updating karma, I think also karma-typescript should be taken into account:

> karma-typescript@4.1.1 requires a peer of karma@1 || 2 || 3 || 4 but none is installed. You must install peer dependencies yourself.

**Comment by kilchenmann** [comment]
> When updating karma, I think also karma-typescript should be taken into account:

You're right

**Pull request merged**
