### PR TITLE
feat(admin): Add custom converters for collection types

### LINKED ISSUE #92: Users endpoint: missing values
I don't get all values in the UserResponse?

Direct API call: http://0.0.0.0:3333/admin/users/username/root
```json
"user": {
    "email": "root@example.com",
    "familyName": "Administrator",
    "givenName": "System",
    "groups": [],
    "id": "http://rdfh.ch/users/root",
    "lang": "de",
    "password": null,
    "permissions": {
        "administrativePermissionsPerProject": {},
        "groupsPerProject": {
            "http://www.knora.org/ontology/knora-admin#SystemProject": [
                "http://www.knora.org/ontology/knora-admin#SystemAdmin"
            ]
        }
    },
    "projects": [],
    "sessionId": null,
    "status": true,
    "token": null,
    "username": "root"
}
```

Console.log of response from `knoraApiConnection.admin.usersEndpoint.getUserByUsername(this.username)`:

Screenshot 2019-11-04 at 10 12 59

### LINKED ISSUE #97: Use json2typescript when submitting payloads in admin api
For put and post operations with payload in the admin API, this.jsonConvert.serializeObject(payload) should be called.

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR adds implementations of `JsonCustomConvert` to handle the collections that are objects of the properties `administrativePermissionsPerProject` and `groupsPerProject` in the class `PermissionsData`.

Resolves #92.
Resolves #97.
Closes #98.
Needs https://github.com/dasch-swiss/knora-api/pull/1505.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@benjamingeer This looks good, thank you! I will check this iPR with @kilchenmann today.

**Comment by tobiasschweizer** [comment]
> I wanted to use the builded package of this branch in the knora-ui or in the knora-api-js-lib-test app, but I got on both branches the following errors: 

I have spotted this behavior as well in https://github.com/dasch-swiss/knora-api-js-lib-test/pull/21 when the e2e test ran on travis.

I could reproduce this locally with `yarn` when building @knora/api.

Please try the following:

- run `npm i` in your @knora/api project root
- run `yalc remove --all`
- run `npm run yalc-publish`

In @knora/api we use `npm` and have an package-lock.json, but there is not `yarn.lock`.

Then install the local package in your app with `yarn`

**Comment by tobiasschweizer** [comment]
see https://github.com/dasch-swiss/knora-api-js-lib-test/blob/c3e533ebb91361cf81de1eff01603bac7c8dc750/.travis.yml#L39

**Comment by kilchenmann** [comment]
> I could reproduce this locally with yarn when building @knora/api.

Thanks @tobiasschweizer. It's seems to be an issue with the dependencies. `npm install` fixed it because of missing PhantomJS and core-js. I thought last time it wasn't a problem with yarn. But you're right, we should use npm in this library. Now I can review it..

**Comment by benjamingeer** [comment]
Thanks @tobiasschweizer and @kilchenmann for your help with this!

**Pull request merged**
