### PR TITLE
Fix import from index.ts

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR fixes an import from `index.ts` that resulted in a circular dep.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
> I was going to write to you about that circular dependency. thanks for fixing it.

My IDE likes to import from `index.ts` although it should not ...

**Comment by SepidehAlassi** [comment]
@tobiasschweizer mine does the same. you also use Webstorm, don't you? I noticed the warnings on the command line.

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer mine does the same. you also use Webstorm, don't you? I noticed the warnings on the command line.

Webstorm offers multiple imports, the one from `index.ts` being the default. You can also choose a different path, but that is not the default behaviour. I wonder if this can be changed.

**Comment by SepidehAlassi** [comment]
I have tried this fix, it works fine. You can merge this PR.

**Comment by tobiasschweizer** [comment]
> I have tried this fix, it works fine. You can merge this PR.

Thx. Just waiting for the tests to pass ...

**Pull request merged**
