### PR TITLE
ontology IRI: ignore port if not running on localhost

### PR DESCRIPTION
**Pull request by loicjaouen**
follow knora's recipe for forging an IRI: https://github.com/dasch-swiss/knora-api/blob/0127dcae27e46bc3a4c9947282c30038c0a25d20/webapi/src/main/scala/org/knora/webapi/Settings.scala#L54

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@loicjaouen I would be great if you could add a test case to `src/models/v2/ontologies/OntologyConversionUtil.spec.ts`.

You can copy the existing `describe`, add it below and adapt the `apiHost` setting for `KnoraApiConfig`. 

Thanks a lot!

**Comment by loicjaouen** [comment]
apologies @tobiasschweizer I only now read your comment and I added the tests differently, do you mind?

**Comment by tobiasschweizer** [comment]
> I only now read your comment and I added the tests differently, do you mind?

Could you make it two `describe` blocks, each having their own config object? And then they just contain the same `it`s, with different expectations of course.

```ts
describe("Method getOntologyIriFromEntityIri with local setup", () => {

        const config = new KnoraApiConfig("http", "0.0.0.0", 3333);

        it("should get the ontology IRI from a knora-api entity", () => {
          ...
        });

}

describe("Method getOntologyIriFromEntityIri with remote setup", () => {

        const config = new KnoraApiConfig("https", "test.example.com", 3333);

        it("should get the ontology IRI from a knora-api entity", () => {
          ...
        });

}
```

This way it's very clear that in one case your are testing a local config and a remote config in the other.

Sorry for being annoying with this ...

**Comment by loicjaouen** [comment]
no problem, as you wish :)

**Comment by tobiasschweizer** [comment]
Ok, good to go! Thanks a lot, @loicjaouen.

**Comment by loicjaouen** [comment]
thank you @tobiasschweizer and @subotic  :)

**Comment by tobiasschweizer** [comment]
@loicjaouen I merged your PR, I hope you don't mind.

**Comment by loicjaouen** [comment]
perfect, thanks (I updated the branch and was waiting for the test to complete)

**Pull request merged**
