### PR TITLE
Automate client code integration

### PR DESCRIPTION
**Pull request by tobiasschweizer**
relates to https://github.com/dasch-swiss/knora-api/issues/1554

### CODE REVIEW

**Comment by subotic** [comment]
There is an issue with `tar` and `zip` files when used on Linux, which produces the following error:
```
tar -C /tmp/ts -xf /tmp/ts.zip
679
tar: This does not look like a tar archive
680
tar: Exiting with failure status due to previous errors
681
make[2]: *** [generate-client-code] Error 2
682
make[1]: *** [test] Error 2
```

Can you maybe try to use `unzip`?

**Comment by tobiasschweizer** [comment]
@subotic Please try again

**Comment by subotic** [comment]
it works now :-)

**Comment by tobiasschweizer** [comment]
@subotic Ok, now you can use `master`.

**Pull request merged**
