### PR TITLE
Mock Ontology Data

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Mock data for https://dasch.myjetbrains.com/youtrack/issue/DSP-401.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@flavens I added a mock for projects.

You can use it like shown here: https://github.com/dasch-swiss/knora-api-js-lib/blob/712ca426f17475f600548d02b64896d530615680/test-framework/src/app/app.component.ts#L70

**Comment by tobiasschweizer** [comment]
@flavens https://github.com/dasch-swiss/knora-api-js-lib/pull/199/commits/06382e23eda24fd55dc2065f39868ff0325f1249 adds a single project

**Comment by flavens** [comment]
@tobiasschweizer is it possible to merge this PR asap and create a new release of dsp-js with it?

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer is it possible to merge this PR asap and create a new release of dsp-js with it?

I will try to use the mocked ontology in the advanced search migration branch. If it works, I will request your review for this PR.

**Comment by tobiasschweizer** [comment]
@flavens Could you please review this PR? Then later we can make a new version. But I think we will make another small PR for that.

**Pull request merged**
