### PR TITLE
Add missing constants for file values

### LINKED ISSUE #112: Missing constants
Can someone add the following definitions to [constants file](https://github.com/dasch-swiss/knora-api-js-lib/blob/master/src/models/v2/Constants.ts)?

- FileValue
- AudioFileValue
  - AuidoFileValueHasDuration
- DDDFileValue
- DocumentFileValue
- MovingImageFileValue
  - MovingImageFileValueHasDimX
  - MovingImageFileValueHasDimY
  - MovingImageFileValueHasDuration
  - MovingImageFileValueHasFps
- TextFileValue

- hasAudioFileValue
- hasDDDFileValue
- hasDocumentFileValue
- hasMovingImageFileValue
- hasTextFileValue
- hasStillImageFileValue

And something for the default permission groups, e.g.:

```typescript
static KnoraOntologyPath: string = 'http://www.knora.org/ontology';
static KnoraAdmin: string = Constants.KnoraOntologyPath + '/knora-admin';
static DefaultSharedOntologyIRI: string = Constants.KnoraAdmin + '#DefaultSharedOntologiesProject';
static SystemProjectIRI: string = Constants.KnoraAdmin + '#SystemProject';
static SystemAdminGroupIRI: string = Constants.KnoraAdmin + '#SystemAdmin';
static ProjectAdminGroupIRI: string = Constants.KnoraAdmin + '#ProjectAdmin';
static ProjectMemberGroupIRI: string = Constants.KnoraAdmin + '#ProjectMember';
```

### LINKED ISSUE #117: @knora/api has no exported member
- RegionGeometry
- Point2D
- KnoraDate
- KnoraPeriod
- ReadDateValue
- Precision

### PR DESCRIPTION
**Pull request by tobiasschweizer**
closes #112 
closes #117

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@kilchenmann I added the constants you mentioned in #112. So far, `StillImageValue` is the only one that is supported in `ResourcesConversionUtil` (conversion from JSON-LD to TS).

**Comment by kilchenmann** [comment]
Thanks @tobiasschweizer. When will this PR be merged?

**Comment by kilchenmann** [comment]
The following constants have missing value `/knora-admin`:

- DefaultSharedOntologyIRI
- SystemProjectIRI
- SystemAdminGroupIR
- ProjectAdminGroupIRI
- ProjectMemberGroupIRI

**Comment by tobiasschweizer** [comment]
> The following constants have missing value /knora-admin:

> DefaultSharedOntologyIRI
> SystemProjectIRI
> SystemAdminGroupIR
> ProjectAdminGroupIRI
> ProjectMemberGroupIRI

Are those correct?

https://github.com/dasch-swiss/knora-api-js-lib/blob/481614f53a9fa19f4b744f9e24986430d0ab6d97/src/models/v2/Constants.ts#L108-L112

**Comment by tobiasschweizer** [comment]
@kilchenmann 

> What's about KnoraSchema?

> export enum KnoraSchema {
>     complex = 0,
>     simple = 1
> }
> 

knora-api-lib-js works exclusively with Api v2 complex. Simple was used for Gravsearch but has been refactored to complex.

**Comment by kilchenmann** [comment]
> Are those correct?

No. We did it like this:

https://github.com/dasch-swiss/knora-ui/blob/a59640e09331ad3aea57ba00b97706f8861fd98d/projects/knora/core/src/lib/declarations/api/knora-constants.ts#L9-L17

I mean `knoraAdmin` should have value `http://www.knora.org/ontology/knora-admin`

**Pull request merged**
